const defaultTheme = require("tailwindcss/defaultTheme");

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      borderRadius: {
        none: "0px",
        sm: "0.5rem",
        DEFAULT: "0.75rem",
        md: "0.875rem",
        lg: "var(--radius)",
        xl: "1rem",
        "2xl": "1.375rem",
        "3xl": "1.75rem",
      },
      fontFamily: {
        sans: ['"SF Pro Text"', '"SF Pro Display"', "Inter", ...defaultTheme.fontFamily.sans],
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        emerald: {
          50: "#eefaf8",
          100: "#d8f3ef",
          200: "#afe6dc",
          300: "#86d8ca",
          400: "#5ccab8",
          500: "#37b8a7",
          600: "#1f9c8d",
          700: "#17796d",
          800: "#11574f",
          900: "#0b3a34",
          950: "#072624",
        },
        sky: {
          50: "#eef8fb",
          100: "#d8edf5",
          200: "#b6dced",
          300: "#8fc8e2",
          400: "#65b3d4",
          500: "#4398c0",
          600: "#31789b",
          700: "#285f7b",
          800: "#224f64",
          900: "#1f4254",
          950: "#132939",
        },
        blue: {
          50: "#eef5f8",
          100: "#dce9ef",
          200: "#c1d7e3",
          300: "#9cbcd0",
          400: "#739cb8",
          500: "#567d9f",
          600: "#456483",
          700: "#3b526b",
          800: "#36475a",
          900: "#313d4d",
          950: "#202834",
        },
        amber: {
          50: "#fff9ef",
          100: "#ffefd1",
          200: "#ffdea0",
          300: "#ffcb6d",
          400: "#f7b846",
          500: "#e8a125",
          600: "#c67f18",
          700: "#9e6015",
          800: "#814d17",
          900: "#6b4118",
          950: "#3d2209",
        },
        purple: {
          50: "#f1f7fa",
          100: "#dbeaf2",
          200: "#bdd8e7",
          300: "#97c0d8",
          400: "#6da4c5",
          500: "#4c88ad",
          600: "#3a6d8d",
          700: "#315872",
          800: "#2d4c61",
          900: "#2a4152",
          950: "#1a2934",
        },
        red: {
          50: "#fdf3f2",
          100: "#fbe6e4",
          200: "#f8d1cc",
          300: "#f2aea5",
          400: "#e77f72",
          500: "#db5848",
          600: "#c83f31",
          700: "#a73227",
          800: "#8a2c24",
          900: "#732a24",
          950: "#3e1210",
        },
      },
      boxShadow: {
        "fp-soft": "0 12px 34px rgba(16, 42, 52, 0.12)",
        "fp-card": "0 8px 24px rgba(16, 42, 52, 0.10)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
